// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaFH-m-mBbxjGw0SZKuehmES9oncVOuxY',
    appId: '1:90494504912:web:8d9633823d95e61ecf33d5',
    messagingSenderId: '90494504912',
    projectId: 'resume-builder-bbc5f',
    authDomain: 'resume-builder-bbc5f.firebaseapp.com',
    storageBucket: 'resume-builder-bbc5f.appspot.com',
    measurementId: 'G-GDXZVB22ZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFWSagHv4F3S8L6fulaFifYtu6JPTDFt4',
    appId: '1:90494504912:android:bfe4abe58149f6b2cf33d5',
    messagingSenderId: '90494504912',
    projectId: 'resume-builder-bbc5f',
    storageBucket: 'resume-builder-bbc5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvWUtaELZdaW5Az9xRcyvH6io9-6ZcTnQ',
    appId: '1:90494504912:ios:9237f29c10088d0ecf33d5',
    messagingSenderId: '90494504912',
    projectId: 'resume-builder-bbc5f',
    storageBucket: 'resume-builder-bbc5f.appspot.com',
    iosBundleId: 'com.example.flutterResumeBuilder',
  );
}
